export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

 export const USER_LOGIN_REQUEST=`USER_LOGIN_REQUEST`;
export const USER_LOGIN_SUCCESS=`USER_LOGIN_SUCCESS`;
export const USER_LOGIN_ERROR=`USER_LOGIN_ERROR`;
 
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
